---
version: '2'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.cisco.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.99.102'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'

    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'

  #jenkins:
  #  build: ./jenkins
  #  build:
    #  context: ./jenkins
    #  dockerfile: Dockerfile
    #   image: jenkins-ansible
    # image: jenkins-ansible
    # container_name: jenkins-ansible
    # restart: always
    # hostname: jenkins
    # ports:
    #   - '8080:8080'
    #   - '50000:50000'
